# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings specified in this file will override any Gradle settings
# configured in the IDE options menu.

# Specifies the JVM arguments used for the Gradle Daemon.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Use AndroidX components
android.useAndroidX=true

# Kotlin code style
kotlin.code.style=official

# Enable non-transitive R classes
android.nonTransitiveRClass=true
